/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GuessTheNumber;

public class App {

  public static void main(String[] args) {
    new GuessTheNumberGame().main(args);
  }
}
